server:
  port: 8090

spring:
  application:
    name: leafw-admin
  datasource:
    url: jdbc:mysql://localhost:3306/leafw_admin?characterEncoding=UTF-8
    username: root
    password: root10086
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      database: 0
      host: localhost
      password:
      port: 6379
  security:
    user:
      name: root
      password: 10086
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
